// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvFQamsWMVRkYYtnzG9hldOal8I6_Lbj8',
    appId: '1:260391164251:web:9daf49fc5950a50dbfa27e',
    messagingSenderId: '260391164251',
    projectId: 'currency-converter-app-6abdd',
    authDomain: 'currency-converter-app-6abdd.firebaseapp.com',
    storageBucket: 'currency-converter-app-6abdd.firebasestorage.app',
    measurementId: 'G-75HZLMTYM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKULh-IlxxFqm3JQddoh0PS9PvM2oXEZk',
    appId: '1:260391164251:android:144070e912c286aebfa27e',
    messagingSenderId: '260391164251',
    projectId: 'currency-converter-app-6abdd',
    storageBucket: 'currency-converter-app-6abdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoegY7H_bkbokW5abt40b_V0cDkyTlwAM',
    appId: '1:260391164251:ios:2f099379d3a780f8bfa27e',
    messagingSenderId: '260391164251',
    projectId: 'currency-converter-app-6abdd',
    storageBucket: 'currency-converter-app-6abdd.firebasestorage.app',
    iosBundleId: 'com.example.currencyRateCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoegY7H_bkbokW5abt40b_V0cDkyTlwAM',
    appId: '1:260391164251:ios:2f099379d3a780f8bfa27e',
    messagingSenderId: '260391164251',
    projectId: 'currency-converter-app-6abdd',
    storageBucket: 'currency-converter-app-6abdd.firebasestorage.app',
    iosBundleId: 'com.example.currencyRateCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvFQamsWMVRkYYtnzG9hldOal8I6_Lbj8',
    appId: '1:260391164251:web:68b2487951c865eabfa27e',
    messagingSenderId: '260391164251',
    projectId: 'currency-converter-app-6abdd',
    authDomain: 'currency-converter-app-6abdd.firebaseapp.com',
    storageBucket: 'currency-converter-app-6abdd.firebasestorage.app',
    measurementId: 'G-TKL36KL3Y4',
  );
}
